name: .NET

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run:  dotnet restore
    - name: Build
      run:  dotnet build -c Release --no-restore
    - name: Test
      run:  dotnet test --no-build
    - name: Upload library binary
      uses: actions/upload-artifact@v2
        name: Geometry.dll
        path: Geometry/bin/Release/Geometry.dll
      if: success()
