name: Pre-release

on:
  push:
    branches:
    - main

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build projects
      run: dotnet build --configuration Release --no-restore
    - name: Upload test artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: test_artifacts
        path: Geometry.Tests/bin/Release/net5.0
    - name: Upload release artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: release_artifacts
        path: Geometry/bin/Release/net5.0/Geometry.dll

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.x
    - name: Download test artifacts
      uses: actions/download-artifact@v2.0.9
      with:
        name: test_artifacts
        path: ./test_artifacts
    - name: Run tests
      working-directory: ./test_artifacts
      run: dotnet test Geometry.Tests.dll

  Pre-release:
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2.0.9
      with:
        name: release_artifacts
        path: ./release_artifacts
    - name: Generate pre-release
      uses: marvinpinto/action-automatic-releases@v1.2.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: true
        title: Development Build
        files:
          ./release_artifacts/Geometry.dll
          