name: Build_and_Test

on:
  push:
  pull_request:

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.x
  Format:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
    - name: Install dotnet-format
      run: dotnet tool install --global dotnet-format --version 5.1.*
    - name: Run dotnet-format
      run: dotnet-format dotnet-ci-example.sln
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.11.0
      with:
        commit_message: Automated formatting
  Install_Deps:
    needs: Format
    runs-on: ubuntu-latest
    steps:
    - run: dotnet restore
  Build:
    needs: Install_Deps
    runs-on: ubuntu-latest
    steps:
    - run: dotnet build --configuration Release --no-restore
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - run: dotnet test --configuration Release --no-build
